version: "3.9"

volumes:
  mysql_vol:
  dbeaver_vol:


networks:
  mysql_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      mysql_net:
        ipv4_address: 172.16.1.10
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_DATABASE=b3
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - 8978:8978
    volumes:
      - dbeaver_vol:/opt/cloudbeaver/workspace
    networks:
      mysql_net:
        ipv4_address: 172.16.1.20
    depends_on:
      mysql:
        condition: service_healthy
